name: Compile Nesca EXE
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '5.15.2'
          host: 'windows'
          target: 'desktop'
          arch: 'win64_mingw81'

      - name: Build Project
        shell: cmd
        run: |
          powershell -Command "(gc nesca_3.pro) -replace 'RC_ICONS\s*=.*', '' | Out-File nesca_3.pro -Encoding UTF8"
          mkdir build
          cd build
          qmake ../nesca_3.pro -spec win32-g++
          mingw32-make

      - name: Pack with windeployqt
        shell: cmd
        run: |
          cd build
          windeployqt nesca_3.exe --no-compiler-runtime --no-opengl-sw || windeployqt release/nesca_3.exe --no-compiler-runtime --no-opengl-sw
          powershell Compress-Archive -Path * -DestinationPath ../nesca_windows.zip

      - name: Upload Finished ZIP
        uses: actions/upload-artifact@v4
        with:
          name: nesca-ready-to-run
          path: nesca_windows.zip
